### ISSUE TITLE
Repository Organization

### ISSUE THREAD

**Issue by sultanalbogami** [UNCG-CSE/Budget_Text_Analysis#17]
For better organization of the project repository please consider the following:

1- Every src folder must have two sub-folders: original and sentiment. Folder names must follow this format: FolderName. Consider abbreviations if the folder name contains more than three words. For instance, a folder named ExploratoryTextDataAnalysis may be abbreviated as ETDA. Please create/rename the folders accordingly and place your notebooks in the corresponding folder. 

2- Every IPython Notebook must adopt the following naming format: Name-Of-The-Notebook.ipynb. Please create/rename your notebooks accordingly.

**Comment by AlbogamiSultan** [comment]
Repository organization is done. Please take a look at the src folders and make sure that your notebooks have been placed in the correct folders. Any future commit that includes the addition of an IPython Notebook or a sub src folder must follow the guidelines specified in this issue.

**Comment by AlbogamiSultan** [comment]
I didn’t take into consideration item no. 2 when I closed this issue. Therefore, issue remains open. Please rename your notebooks according to item no. 2.
