### ISSUE TITLE
Removing stop words from original.csv for Topic Modelling

### ISSUE THREAD

**Issue by naseebth** [UNCG-CSE/Budget_Text_Analysis#7]
Work on getting familiar with the pandas dataframe. Search for ways to remove stopwords, clean the data, and, prepare the data for Topic Modelling. Use the original data csv for the task.

**Comment by AlbogamiSultan** [comment]
As part of data pre-processing for topic modelling, I did the following: 
1- Transformed all words into lower case.
2- Corrected spelling mistakes if there is any.
3- Lemmatization - Converted the words into their root words.
4- Counted stopwords in data.
5- Removed stop words. 

Issue has been resolved.
